import { SonarFinding } from '@/types/todo';

export const SONAR_FINDINGS: SonarFinding[] = [
  {
    id: 'SONAR-001',
    ruleKey: 'typescript:S2068',
    title: 'Hard-coded credentials / secrets',
    type: 'VULNERABILITY',
    severity: 'BLOCKER',
    filePath: 'lib/api-client.ts',
    line: 9,
    codeSnippet: 'const API_SECRET_KEY = "ghp_prod_admin_secret_token_984592019482";',
    description: 'Storing secrets directly in source code exposes credentials to anyone with repository access.',
    remediation: 'Use environment variables (process.env.API_SECRET_KEY) or a secure secret manager vault.'
  },
  {
    id: 'SONAR-002',
    ruleKey: 'typescript:S5131',
    title: 'DOM XSS via dangerouslySetInnerHTML',
    type: 'VULNERABILITY',
    severity: 'BLOCKER',
    filePath: 'components/TodoItem.tsx',
    line: 114,
    codeSnippet: '<div dangerouslySetInnerHTML={{ __html: todo.notesHtml }} />',
    description: 'Directly injecting unsanitized HTML allows Cross-Site Scripting (XSS) attacks if user input is rendered.',
    remediation: 'Sanitize HTML with DOMPurify or render plain text.'
  },
  {
    id: 'SONAR-003',
    ruleKey: 'typescript:S2245',
    title: 'Pseudorandom number generator is not cryptographically secure',
    type: 'SECURITY_HOTSPOT',
    severity: 'CRITICAL',
    filePath: 'lib/todo-utils.ts',
    line: 45,
    codeSnippet: 'const token = "tok_" + Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2);',
    description: 'Math.random() is predictable and should not be used to generate security tokens or sensitive identifiers.',
    remediation: 'Use crypto.randomUUID() or crypto.getRandomValues() for security-sensitive tokens.'
  },
  {
    id: 'SONAR-004',
    ruleKey: 'typescript:S5852',
    title: 'Using regular expressions vulnerable to polynomial or exponential backtracking (ReDoS)',
    type: 'SECURITY_HOTSPOT',
    severity: 'CRITICAL',
    filePath: 'lib/todo-utils.ts',
    line: 60,
    codeSnippet: 'const TAG_VALIDATION_REGEX = /^([a-zA-Z0-9]+_?)*$/;',
    description: 'Nested quantifiers without boundary checks can cause exponential backtracking and Denial of Service (ReDoS).',
    remediation: 'Simplify regex to avoid overlapping quantifiers, e.g. /^[a-zA-Z0-9]+(_[a-zA-Z0-9]+)*$/.'
  },
  {
    id: 'SONAR-005',
    ruleKey: 'typescript:S5144',
    title: 'Server-Side Request Forgery / Unsafe external target link',
    type: 'VULNERABILITY',
    severity: 'MAJOR',
    filePath: 'components/TodoItem.tsx',
    line: 128,
    codeSnippet: '<a href={todo.externalLink} target="_blank">',
    description: 'Target _blank without rel="noopener noreferrer" exposes window.opener and unvalidated href allows javascript: URLs.',
    remediation: 'Add rel="noopener noreferrer" and validate that protocol starts with http:// or https://.'
  },
  {
    id: 'SONAR-006',
    ruleKey: 'typescript:S2692',
    title: 'indexOf check is faulty (indexOf > 0 instead of >= 0)',
    type: 'BUG',
    severity: 'CRITICAL',
    filePath: 'lib/todo-utils.ts',
    line: 78,
    codeSnippet: 'return todo.title.toLowerCase().indexOf(term.toLowerCase()) > 0;',
    description: 'When a match occurs at index 0 (at the very beginning of the string), indexOf returns 0, making this expression evaluate to false.',
    remediation: 'Change `> 0` to `>= 0` or use `todo.title.toLowerCase().includes(term.toLowerCase())`.'
  },
  {
    id: 'SONAR-007',
    ruleKey: 'typescript:S1764',
    title: 'Identical sub-expressions on both sides of binary operator',
    type: 'BUG',
    severity: 'CRITICAL',
    filePath: 'lib/todo-store.ts',
    line: 38,
    codeSnippet: 'const hasDuplicate = todos.some(t => t.id === t.id);',
    description: 'Comparing an expression to itself (t.id === t.id) always evaluates to true, rendering the logic useless.',
    remediation: 'Compare against target ID: `t.id === targetId && t !== targetTodo`.'
  },
  {
    id: 'SONAR-008',
    ruleKey: 'typescript:S128',
    title: 'Switch cases should end with unconditional break statement',
    type: 'BUG',
    severity: 'CRITICAL',
    filePath: 'lib/todo-utils.ts',
    line: 104,
    codeSnippet: 'case "urgent": weight += 10; // Missing break (fallthrough to high)',
    description: 'Missing break or return causes unintended fall-through execution to subsequent cases.',
    remediation: 'Add `break;` or return immediately from each case.'
  },
  {
    id: 'SONAR-009',
    ruleKey: 'typescript:S2123',
    title: 'Values should not be uselessly incremented',
    type: 'BUG',
    severity: 'MAJOR',
    filePath: 'lib/todo-utils.ts',
    line: 122,
    codeSnippet: 'let count = 0; count = count++;',
    description: 'Postfix increment evaluates to the old value before assignment, resulting in count remaining unchanged (0).',
    remediation: 'Use `count++` or `count += 1` without re-assigning to count.'
  },
  {
    id: 'SONAR-010',
    ruleKey: 'typescript:S2589',
    title: 'Boolean expressions should not be gratuitous / always true',
    type: 'BUG',
    severity: 'MAJOR',
    filePath: 'components/TodoList.tsx',
    line: 34,
    codeSnippet: 'if (todos.length >= 0) { /* condition always true */ }',
    description: 'Array.length is always non-negative, so `length >= 0` is redundant and likely a typo for `length > 0`.',
    remediation: 'Use `if (todos.length > 0)` or remove redundant check.'
  },
  {
    id: 'SONAR-011',
    ruleKey: 'typescript:S3776',
    title: 'Cognitive Complexity of function should not be too high',
    type: 'CODE_SMELL',
    severity: 'CRITICAL',
    filePath: 'lib/todo-utils.ts',
    line: 140,
    codeSnippet: 'export function filterAndSortTodosComplex(todos: TodoItem[], ...)',
    description: 'Function contains deeply nested if/else statements, loops, and nested ternaries exceeding threshold (Cognitive Complexity > 15).',
    remediation: 'Refactor into smaller single-responsibility helper functions.'
  },
  {
    id: 'SONAR-012',
    ruleKey: 'typescript:S3358',
    title: 'Ternary operators should not be nested',
    type: 'CODE_SMELL',
    severity: 'MAJOR',
    filePath: 'components/TodoBadge.tsx',
    line: 18,
    codeSnippet: 'priority === "urgent" ? "bg-red-600" : priority === "high" ? "bg-orange-500" : priority === "medium" ? "bg-yellow-500" : "bg-blue-500"',
    description: 'Deeply nested ternary operators significantly reduce readability and maintainability.',
    remediation: 'Use a dictionary lookup map or a clean switch/if-else function.'
  },
  {
    id: 'SONAR-013',
    ruleKey: 'typescript:S1871',
    title: 'Two branches in a conditional structure should not have exactly the same implementation',
    type: 'CODE_SMELL',
    severity: 'MAJOR',
    filePath: 'lib/todo-utils.ts',
    line: 198,
    codeSnippet: 'if (category === "work") { return "bg-indigo-100 text-indigo-800"; } else if (category === "finance") { return "bg-indigo-100 text-indigo-800"; }',
    description: 'Duplicate branch bodies make code harder to maintain and often indicate copy-paste mistakes.',
    remediation: 'Combine conditions using logical OR: `if (category === "work" || category === "finance")`.'
  },
  {
    id: 'SONAR-014',
    ruleKey: 'typescript:S3626',
    title: 'Jump statements should not be redundant',
    type: 'CODE_SMELL',
    severity: 'MINOR',
    filePath: 'lib/todo-utils.ts',
    line: 220,
    codeSnippet: 'if (new Date(todo.dueDate).getTime() < Date.now()) { return true; } else { return false; }',
    description: 'Writing `if (cond) return true; else return false;` is verbose and redundant.',
    remediation: 'Return condition directly: `return new Date(todo.dueDate).getTime() < Date.now();`.'
  },
  {
    id: 'SONAR-015',
    ruleKey: 'typescript:S107',
    title: 'Functions should not have too many parameters (> 7 parameters)',
    type: 'CODE_SMELL',
    severity: 'MAJOR',
    filePath: 'lib/todo-utils.ts',
    line: 236,
    codeSnippet: 'export function createDetailedTodoItem(title, desc, priority, category, tags, dueDate, link, notes, token, isDone)',
    description: 'Functions with more than 7 parameters violate clean code principles and lead to argument order errors.',
    remediation: 'Pass a configuration object or interface parameter instead.'
  },
  {
    id: 'SONAR-016',
    ruleKey: 'typescript:S1854',
    title: 'Unused assignments (Dead stores) should be removed',
    type: 'CODE_SMELL',
    severity: 'MINOR',
    filePath: 'lib/todo-utils.ts',
    line: 260,
    codeSnippet: 'let formattedTitle = title.trim(); formattedTitle = title.toUpperCase(); // Dead store',
    description: 'The first assignment to `formattedTitle` is immediately overwritten without being read.',
    remediation: 'Remove the redundant initial assignment.'
  },
  {
    id: 'SONAR-017',
    ruleKey: 'typescript:S2486',
    title: 'Generic exceptions should not be ignored silently',
    type: 'CODE_SMELL',
    severity: 'CRITICAL',
    filePath: 'lib/todo-store.ts',
    line: 24,
    codeSnippet: 'try { return JSON.parse(stored); } catch (e) { /* silent swallow */ }',
    description: 'Empty catch block swallows errors without logging or handling, making debugging difficult.',
    remediation: 'Log the error or provide a fallback strategy with informative reporting.'
  },
  {
    id: 'SONAR-018',
    ruleKey: 'typescript:S1186',
    title: 'Methods should not be empty',
    type: 'CODE_SMELL',
    severity: 'MINOR',
    filePath: 'components/TodoForm.tsx',
    line: 52,
    codeSnippet: 'const onQuickAction = () => {};',
    description: 'Empty functions either indicate unfinished work or unnecessary handlers.',
    remediation: 'Implement functionality or add a comment explaining why the function is empty.'
  },
  {
    id: 'SONAR-019',
    ruleKey: 'typescript:S106',
    title: 'Standard outputs should not be used directly in production code',
    type: 'CODE_SMELL',
    severity: 'MINOR',
    filePath: 'lib/api-client.ts',
    line: 28,
    codeSnippet: 'console.log("[DEBUG API] Syncing todo item to remote cloud:", payload);',
    description: 'console.log statements left in production code can leak sensitive data and clutter runtime logs.',
    remediation: 'Use a structured logging framework with configurable log levels.'
  },
  {
    id: 'SONAR-020',
    ruleKey: 'typescript:S1135',
    title: 'Track uses of "TODO" and "FIXME" tags',
    type: 'CODE_SMELL',
    severity: 'INFO',
    filePath: 'lib/todo-utils.ts',
    line: 12,
    codeSnippet: '// TODO: Implement server side syncing and offline database synchronization\n// FIXME: Fix time zone bug when parsing UTC dates',
    description: 'Unresolved TODO/FIXME markers in production code indicate technical debt.',
    remediation: 'Resolve the issue or track it in a project management issue tracker.'
  },
  {
    id: 'SONAR-021',
    ruleKey: 'typescript:S1481',
    title: 'Unused local variables and imports should be removed',
    type: 'CODE_SMELL',
    severity: 'MINOR',
    filePath: 'lib/api-client.ts',
    line: 15,
    codeSnippet: 'const unusedDefaultTimeout = 30000; const unusedRetryAttempts = 3;',
    description: 'Variables defined but never read increase cognitive clutter and memory consumption.',
    remediation: 'Delete unused variables.'
  },
  {
    id: 'SONAR-022',
    ruleKey: 'typescript:S6440',
    title: 'Do not use array index as React key',
    type: 'CODE_SMELL',
    severity: 'MAJOR',
    filePath: 'components/TodoList.tsx',
    line: 56,
    codeSnippet: '{filteredTodos.map((todo, index) => <TodoItem key={index} ... />)}',
    description: 'Using array index as key in dynamic lists degrades React reconciliation and causes rendering bugs when items are reordered or deleted.',
    remediation: 'Use unique stable identifier `key={todo.id}`.'
  },
  {
    id: 'SONAR-023',
    ruleKey: 'common-ts:DuplicatedBlocks',
    title: 'Source code contains duplicated blocks',
    type: 'DUPLICATION',
    severity: 'MAJOR',
    filePath: 'lib/export-helpers.ts',
    line: 42,
    codeSnippet: '// ~30 lines of identical header formatting and metadata parsing duplicated between CSV and JSON export routines',
    description: 'Duplicated code increases maintenance effort and bug risk when one copy is updated and another is forgotten.',
    remediation: 'Extract common formatting and serialization logic into reusable helper functions.'
  }
];
